spring:
  application:
    name: slack-service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8087

eureka:
  client:
    register-with-eureka: true # Eureka? ??? ??
    fetch-registry: true # Eureka?? ??? ?? ????
    service-url:
     defaultZone: http://localhost:8761/eureka/