spring:
  application:
    name: slack-service
  datasource:
    url: jdbc:postgresql://localhost:5001/msa_db  # Docker의 PostgreSQL 컨테이너의 IP 또는 호스트와 포트를 사용
    username: postgres_msa  # PostgreSQL 사용자 이름
    password: 12345  # PostgreSQL 비밀번호
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: slacks
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL에 맞는 Hibernate Dialect 설정
  h2:
    console:
      enabled: false  # H2 콘솔 비활성화 (PostgreSQL 사용 시)

server:
  port: 8087

eureka:
  client:
    register-with-eureka: true # Eureka? ??? ??
    fetch-registry: true # Eureka?? ??? ?? ????
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /slack-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
slack:
  webhook:
    url: https://hooks.slack.com/services/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