#version: '3.8'
#
#services:
#  # PostgreSQL 데이터베이스 설정
#  postgres:
#    image: postgres:latest
#    container_name: postgres_user
#    ports:
#      - "5001:5432"  # 외부에서 접속할 수 있는 포트
#    environment:
#      POSTGRES_USER: postgres_user
#      POSTGRES_PASSWORD: 12345
#      POSTGRES_DB: user_db  # 생성할 데이터베이스 이름
#    volumes:
#      - postgres_data:/var/lib/postgresql/data  # 데이터가 유지될 경로
#    networks:
#      - user-network  # user 서비스와만 연결될 네트워크
#
#  # User 서비스
#  user:
#    build:
#      context: .  # user 서브모듈의 디렉토리
#      dockerfile: Dockerfile  # Dockerfile 경로
#    container_name: user
#    ports:
#      - "8001:8001"  # 외부에서 접속할 포트
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_user:5001/user_db  # PostgreSQL DB 연결
#      - SPRING_DATASOURCE_USERNAME=postgres_user  # DB 사용자명
#      - SPRING_DATASOURCE_PASSWORD=12345  # DB 비밀번호
#    networks:
#      - user-network  # user 서비스가 PostgreSQL과 연결될 네트워크
#    depends_on:
#      - postgres  # PostgreSQL이 먼저 실행되어야 함
#
#networks:
#  user-network:
#    driver: bridge  # user 서비스와 PostgreSQL만 연결될 네트워크
#
#volumes:
#  postgres_data:  # PostgreSQL 데이터 저장을 위한 볼륨
